AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: okta-aws-sync - Sample SAM Template for okta-aws-sync.
    
Globals:
    Function:
        Timeout: 3


Resources:
    SyncAWSRoleToOkta:
        Type: AWS::Serverless::Function # More info
        Properties:
            CodeUri: sync-roles/
            Handler: app.lambdaHandler
            Runtime: nodejs8.10
            Environment: # More info
                Variables:
                    PARAM1: VALUE  

#    This part still needs to be completed and tested 
#    EventRule:
#        Type: AWS::Events::Rule 
#        Properties:
#            Description: CloudWatchLogsRule
#                EventPattern:
#                source:
#                - "aws.iam"
#                detail-type:
#                - "AWS API Call via CloudTrail"
#                detail:
#                eventSource:
#                - "iam.amazonaws.com"
#                eventName:
#                - "CreateRole"
#            Name: CW_IAM_API_Trigger_TEST
#          ScheduleExpression: String
#          State: "ENABLED"
#          Targets:
#            - sam-app-hw-SyncAWSRoleToOkta-18K0RCHTI97WZ
#    PermissionForEventsToInvokeLambda:
#        Type: AWS::Lambda::Permission
#        Properties:
#        FunctionName:
#            Ref: "LambdaFunction"
#        Action: "lambda:InvokeFunction"
#        Principal: "events.amazonaws.com"
#        SourceArn:
#            Fn::GetAtt:
#                - "EventRule"
#                - "Arn"
Outputs:
    SyncAWSRoleToOkta:
        Description: Sync AWS Role to Okta Lambda Function ARN
        Value: !GetAtt SyncAWSRoleToOkta.Arn

    SyncAWSRoleToOktaIamRole:
        Description: Implicit IAM Role created for Sync Role function
        Value: !GetAtt SyncAWSRoleToOktaRole.Arn